[package]
name = "csvlm"
version = "0.1.3"
authors = ["Lukas Andreas Muller <lamuller@protonmail.com>"]
description = "Language management through CSV tables"
license = "MIT"
repository = "https://github.com/luki/language-parser-csv"
readme = "README.md"

[dependencies]
